# Generated by Django 2.0.7 on 2018-07-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='FirstBlog')),
                ('body', models.TextField(blank=True, max_length=200, verbose_name='this is my python study lesson , it"s a blog site')),
                ('created_time', models.DateTimeField(verbose_name='发布时间')),
            ],
        ),
    ]
